import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="pt-br">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link 
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Alexandria">
        </link>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
